import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";


import { api } from "../utils/api";

const Home: NextPage = () => {
  // const {}= api.example.test.useQuery({ teststring: "from tRPC" });


  return (
    <>
      <Head>
        <title>Poke Shop</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto my-12 max-q-3xl">
        <div className="flex justify-between">
        <h2 className="text-2xl font-semibold text-black">My Poke-Shop</h2>
        <button type='button' className='bg-sky-50 transition hover:bg-indigo-700 p-2 mx-8 rounded-md text-sm text-white'>Add Pokémon</button>
        </div>
      </main>
      
    </>
  );
};

export default Home
